version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - acubismmotion
  - Aerisita
  - airi
  - airi-vtuber
  - Alaya
  - alexanderolsen
  - alibabacloud
  - aliyun
  - aliyuncs
  - allseto
  - animejs
  - APNG
  - Armbruster
  - astrojs
  - Attributify
  - attw
  - audia
  - audioworklet
  - autoplay
  - awilix
  - Ayaka
  - baichuan
  - baiducloud
  - bailian
  - bigserial
  - bilibili
  - Bitstream
  - bootkit
  - browserbasehq
  - buildless
  - bumpp
  - byteorder
  - Catap
  - catppuccin
  - cdylib
  - cerebras
  - cientos
  - cjkfonts
  - clippy
  - clustr
  - collectblock
  - colorjs
  - cometapi
  - Comfortaa
  - composables
  - cooldown
  - coreml
  - cosyvoice
  - cozyvoice
  - crossws
  - csmmap
  - csmvector
  - csstype
  - cubismbreath
  - cubismdebug
  - cubismdefaultparameterid
  - cubismeyeblink
  - cubismmatrix44
  - cubismmoc
  - cubismmodelsettingjson
  - cubismmotionqueuemanager
  - cubismusermodel
  - cubismviewmatrix
  - cuda
  - culori
  - cuteen
  - dataurl
  - deepseek
  - defu
  - demi
  - demodel
  - destr
  - devlog
  - devlogs
  - directml
  - Dismissable
  - dokidoki
  - dompurify
  - dotenvx
  - DownloadLive2DSDK
  - Downsampling
  - dreamlog
  - dtolnay
  - dtype
  - dtypes
  - duckdb
  - DuckDBWASM
  - DuckDBWASMQ
  - DuckDBWASMQuery
  - eastasia
  - elevenlabs
  - elfutils
  - Equirectangular
  - esaxx
  - eventa
  - Factorio
  - feaxios
  - Flathub
  - flexsearch
  - formkit
  - frontmatter
  - Genshin
  - giteeai
  - gltf
  - gpuu
  - grammyjs
  - groq
  - gugi
  - guii
  - guiiai
  - Hdri
  - hfspaceup
  - hfsup
  - hfup
  - highpass
  - higress
  - histoire
  - hiyori
  - Holo
  - homeassistant
  - huggingface
  - huggingspace
  - hunyuan
  - hyoban
  - iconify
  - injeca
  - injecta
  - intlify
  - jlumbroso
  - jszip
  - Kawaii
  - kebabcase
  - keyup
  - Keyyable
  - kirakira
  - kwaa
  - lemonneko
  - lemonnekogh
  - lerp
  - libsamplerate
  - libsodium
  - lightningcss
  - lipsync
  - listhen
  - live2dcubismcore
  - live2dcubismframework
  - livechat
  - Llmmarker
  - lobehub
  - logg
  - Lorebook
  - lowpass
  - lucide
  - luoling
  - Maekawa
  - magnifer
  - Makito
  - Maru
  - matchall
  - mdit
  - mediabunny
  - mediapipe
  - MeshToonMaterial
  - meteocons
  - micvad
  - mineflayer
  - mingcute
  - minimizable
  - minisearch
  - mkdist
  - modelcontextprotocol
  - modnet
  - moeru
  - Morioki
  - mousedown
  - mouseup
  - msvc
  - multisampling
  - Myriam
  - ndarray
  - Neko
  - nekomeowww
  - nekopaw
  - neuri
  - Neuro
  - Neuro-sama
  - nolyfill
  - nomic
  - novita
  - nprogress
  - nsis
  - nuxi
  - nuxt
  - nuxtjs
  - objc
  - ofetch
  - oklch
  - ollama
  - Oneliner
  - onnx
  - onnxruntime
  - openai
  - openrouter
  - opentype
  - OPFS
  - opusscript
  - otelcol
  - owenthereal
  - oxlint
  - pglite
  - pgvector
  - picklist
  - picovoice
  - pinia
  - pixi
  - pixiv
  - Pmndrs
  - pmrem
  - popmotion
  - poppin
  - posthog
  - PREFLIGHTS
  - prereleased
  - pretrained
  - prismarine
  - prng
  - pthread
  - pulseaudio
  - quanlai
  - qwen
  - rafta
  - Raycaster
  - rdev
  - rehype
  - reka
  - Replayable
  - resampler
  - RGBE
  - rlib
  - rmcp
  - rolldown
  - rushstack
  - Rynco
  - Saccade
  - saccades
  - safetensors
  - SAVEPOINT
  - Screenable
  - sensenova
  - serde
  - Shadcn
  - shenzhen
  - shiki
  - shikijs
  - silero
  - siliconcloud
  - sizecheck
  - smallserial
  - Sniglet
  - sonarjs
  - sonner
  - specta
  - splitpanes
  - splt
  - srgb
  - ssml
  - staticlib
  - stepfun
  - sumimakito
  - supergroup
  - superjson
  - systempreferences
  - tamagotchi
  - tauri
  - taze
  - tempora
  - tinyexec
  - togetherapi
  - tolist
  - tresjs
  - Triggerable
  - tsdown
  - turborepo
  - unbird
  - unbundle
  - unconfig
  - uncrypto
  - unhead
  - Unlisten
  - unocss
  - unplugin
  - unspeech
  - upterm
  - valibot
  - vaul
  - velin
  - VITE
  - vitepress
  - vllm
  - Volcengine
  - vrma
  - vrms
  - vtuber
  - vueuse
  - waapi
  - warpdrive
  - Warudo
  - wavefile
  - webgpu
  - webworkers
  - weeb
  - wgpu
  - wlipsync
  - worklet
  - worklets
  - xast
  - xastscript
  - Xenova
  - xiaolai
  - xsai
  - xsschema
  - zhipu
ignoreWords:
  - smol-toml
import: []
