# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

[toolchain]
channel = "1.89.0"
# https://rust-lang.github.io/rustup/concepts/components.html
components = [
  "rustc",
  "cargo",
  "rustfmt",
  "rust-analyzer",
  "clippy"
]
targets = [
  "x86_64-apple-darwin",
  "aarch64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "aarch64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc"
]
profile = "minimal"
